// components/CompanySplitWizard.js
import React, { useState, useEffect } from 'react';
import {
    Modal,
    Button,
    Form,
    Card,
    Alert,
    ProgressBar,
    Row,
    Col,
    Badge,
    InputGroup
} from 'react-bootstrap';
import { FaBuilding, FaExclamationTriangle, FaInfoCircle, FaSync } from 'react-icons/fa';
import useCompanySplit from '../hooks/useCompanySplit';

const CompanySplitWizard = ({ show, onHide, companies, fiscalYears, currentCompany, onSuccess }) => {
    const [step, setStep] = useState(1);
    const [formData, setFormData] = useState({
        sourceCompanyId: '',
        fiscalYearId: '',
        newCompanyName: '',
        deleteAfterSplit: false
    });
    const [validationErrors, setValidationErrors] = useState({});
    const [autoGeneratedName, setAutoGeneratedName] = useState('');
    const [splitComplete, setSplitComplete] = useState(false);
    const [splitResult, setSplitResult] = useState(null);

    const {
        loading,
        error,
        progress,
        processLog,
        splitCompanyWithSSE,
        cancelSplit,
        reset
    } = useCompanySplit();

    useEffect(() => {
        if (show) {
            // Initialize form with current company
            if (currentCompany) {
                setFormData(prev => ({
                    ...prev,
                    sourceCompanyId: currentCompany.id || currentCompany._id
                }));
            }
            reset();
            setStep(1);
            setAutoGeneratedName('');
            setSplitComplete(false);
            setSplitResult(null);
        }
    }, [show, currentCompany, reset]);

    // Auto-generate company name when source company or fiscal year changes
    useEffect(() => {
        if (formData.sourceCompanyId && formData.fiscalYearId) {
            generateCompanyName();
        }
    }, [formData.sourceCompanyId, formData.fiscalYearId]);

    const generateCompanyName = () => {
        const sourceCompany = companies.find(c => (c.id || c._id) === formData.sourceCompanyId);
        const fiscalYear = fiscalYears.find(fy => (fy.id || fy._id) === formData.fiscalYearId);

        if (sourceCompany && fiscalYear) {
            const newName = `${sourceCompany.name} (${fiscalYear.name || fiscalYear.Name})`;
            setAutoGeneratedName(newName);
            setFormData(prev => ({
                ...prev,
                newCompanyName: newName
            }));
        }
    };

    const handleInputChange = (field, value) => {
        setFormData(prev => ({
            ...prev,
            [field]: value
        }));

        if (validationErrors[field]) {
            setValidationErrors(prev => ({
                ...prev,
                [field]: ''
            }));
        }
    };

    const handleRegenerateName = () => {
        generateCompanyName();
    };

    const validateStep1 = () => {
        const errors = {};

        if (!formData.sourceCompanyId) {
            errors.sourceCompanyId = 'Please select a source company';
        }

        if (!formData.fiscalYearId) {
            errors.fiscalYearId = 'Please select a fiscal year';
        }

        setValidationErrors(errors);
        return Object.keys(errors).length === 0;
    };

    const validateStep2 = () => {
        const errors = {};

        if (!formData.newCompanyName?.trim()) {
            errors.newCompanyName = 'Please enter a name for the new company';
        } else if (formData.newCompanyName.length < 2) {
            errors.newCompanyName = 'Company name must be at least 2 characters long';
        }

        setValidationErrors(errors);
        return Object.keys(errors).length === 0;
    };

    const handleNext = () => {
        if (step === 1 && validateStep1()) {
            setStep(2);
        } else if (step === 2 && validateStep2()) {
            setStep(3);
        }
    };

    const handleBack = () => {
        setStep(step - 1);
    };

    const handleCancel = () => {
        if (loading) {
            cancelSplit();
        }
        reset();
        onHide();
    };

    const handleSubmit = async () => {
        try {
            const result = await splitCompanyWithSSE(formData);
            console.log('Split result:', result);
            
            if (result && !result.cancelled) {
                // Check if we have actual data with new company
                if (result.data && result.data.newCompany) {
                    setSplitComplete(true);
                    setSplitResult(result);
                    
                    setTimeout(() => {
                        if (onSuccess) {
                            onSuccess();
                        }
                        onHide();
                    }, 2000);
                } else if (result.success === false) {
                    setError(result.message || 'Split failed');
                } else if (result.success === true || result.message) {
                    // Even if the result structure is different, mark as complete if it has success
                    setSplitComplete(true);
                    setSplitResult(result);
                    
                    setTimeout(() => {
                        if (onSuccess) {
                            onSuccess();
                        }
                        onHide();
                    }, 2000);
                } else {
                    // Fallback: if we got a result but no clear success, check if we have data
                    if (result.newCompany || result.data) {
                        setSplitComplete(true);
                        setSplitResult(result);
                        
                        setTimeout(() => {
                            if (onSuccess) {
                                onSuccess();
                            }
                            onHide();
                        }, 2000);
                    } else {
                        setError('Split completed but no company data was returned');
                    }
                }
            } else if (result && result.cancelled) {
                // User cancelled, do nothing
                console.log('Split was cancelled by user');
            }
        } catch (err) {
            console.error('Split failed:', err);
            // Don't close the modal on error
        }
    };

    const getSelectedCompany = () => {
        return companies.find(c => (c.id || c._id) === formData.sourceCompanyId);
    };

    const getSelectedFiscalYear = () => {
        return fiscalYears.find(fy => (fy.id || fy._id) === formData.fiscalYearId);
    };

    const getFilteredFiscalYears = () => {
        if (!formData.sourceCompanyId) return [];
        return fiscalYears.filter(fy => {
            const companyId = fy.companyId || fy.company || fy.company_id || fy.CompanyId;
            return companyId === formData.sourceCompanyId;
        });
    };

    const renderStep1 = () => (
        <div>
            <h5 className="mb-4">
                <FaBuilding className="me-2 text-primary" />
                Select Source Company & Fiscal Year
            </h5>

            <Form.Group className="mb-4">
                <Form.Label>Source Company *</Form.Label>
                <Form.Select
                    value={formData.sourceCompanyId}
                    onChange={(e) => handleInputChange('sourceCompanyId', e.target.value)}
                    isInvalid={!!validationErrors.sourceCompanyId}
                >
                    <option value="">Select a company</option>
                    {companies.map(company => (
                        <option key={company.id || company._id} value={company.id || company._id}>
                            {company.name}
                            {(company.id === currentCompany?.id || company._id === currentCompany?._id) && ' (Current)'}
                        </option>
                    ))}
                </Form.Select>
                <Form.Control.Feedback type="invalid">
                    {validationErrors.sourceCompanyId}
                </Form.Control.Feedback>
            </Form.Group>

            <Form.Group className="mb-4">
                <Form.Label>Fiscal Year to Split *</Form.Label>
                <Form.Select
                    value={formData.fiscalYearId}
                    onChange={(e) => handleInputChange('fiscalYearId', e.target.value)}
                    isInvalid={!!validationErrors.fiscalYearId}
                    disabled={!formData.sourceCompanyId}
                >
                    <option value="">Select fiscal year</option>
                    {getFilteredFiscalYears().map(fiscalYear => (
                        <option key={fiscalYear.id || fiscalYear._id} value={fiscalYear.id || fiscalYear._id}>
                            {fiscalYear.name || fiscalYear.Name} (
                            {fiscalYear.startDate
                                ? new Date(fiscalYear.startDate).toLocaleDateString()
                                : fiscalYear.startDateNepali || 'N/A'
                            } -
                            {fiscalYear.endDate
                                ? new Date(fiscalYear.endDate).toLocaleDateString()
                                : fiscalYear.endDateNepali || 'N/A'
                            }
                            )
                            {fiscalYear.isActive && ' (Active)'}
                        </option>
                    ))}
                </Form.Select>
                <Form.Control.Feedback type="invalid">
                    {validationErrors.fiscalYearId}
                </Form.Control.Feedback>
                <Form.Text className="text-muted">
                    Select the fiscal year you want to separate into a new company
                </Form.Text>
            </Form.Group>

            {formData.sourceCompanyId && formData.fiscalYearId && (
                <Alert variant="info">
                    <FaInfoCircle className="me-2" />
                    <strong>Preview:</strong> This will create a new company containing all data from{' '}
                    <strong>{getSelectedCompany()?.name}</strong> for fiscal year{' '}
                    <strong>{getSelectedFiscalYear()?.name || getSelectedFiscalYear()?.Name}</strong>
                    {autoGeneratedName && (
                        <div className="mt-2">
                            <strong>New company name:</strong> {autoGeneratedName}
                        </div>
                    )}
                </Alert>
            )}
        </div>
    );

    const renderStep2 = () => (
        <div>
            <h5 className="mb-4">
                <FaBuilding className="me-2 text-primary" />
                New Company Details
            </h5>

            <Form.Group className="mb-4">
                <Form.Label>New Company Name *</Form.Label>
                <InputGroup>
                    <Form.Control
                        type="text"
                        placeholder="Enter name for the new company"
                        value={formData.newCompanyName}
                        onChange={(e) => handleInputChange('newCompanyName', e.target.value)}
                        isInvalid={!!validationErrors.newCompanyName}
                    />
                    <Button
                        variant="outline-secondary"
                        onClick={handleRegenerateName}
                        title="Regenerate name from source company and fiscal year"
                    >
                        <FaSync />
                    </Button>
                </InputGroup>
                <Form.Control.Feedback type="invalid">
                    {validationErrors.newCompanyName}
                </Form.Control.Feedback>
                <Form.Text className="text-muted">
                    {autoGeneratedName && (
                        <span>
                            Auto-generated name: <strong>{autoGeneratedName}</strong>.
                            You can modify this or click the refresh button to regenerate.
                        </span>
                    )}
                    {!autoGeneratedName && (
                        <span>This will be the name of your new separated company</span>
                    )}
                </Form.Text>
            </Form.Group>

            <Form.Group className="mb-4">
                <Form.Check
                    type="checkbox"
                    label={
                        <span>
                            <strong>Remove the split fiscal year from source company after separation</strong>
                            <br />
                            <small className="text-muted">
                                If checked, the selected fiscal year and its data will be removed from the source company.
                                This action cannot be undone.
                            </small>
                        </span>
                    }
                    checked={formData.deleteAfterSplit}
                    onChange={(e) => handleInputChange('deleteAfterSplit', e.target.checked)}
                />
            </Form.Group>

            <Alert variant="warning">
                <FaExclamationTriangle className="me-2" />
                <strong>Important:</strong> This process may take several minutes depending on your data size.
                Please do not close this window until the process is complete.
            </Alert>
        </div>
    );

    const renderStep3 = () => (
        <div>
            <h5 className="mb-4">
                <FaBuilding className="me-2 text-primary" />
                {loading ? 'Splitting Company...' : splitComplete ? 'Split Complete!' : 'Ready to Split'}
            </h5>

            {!loading && !error && !splitComplete && (
                <Alert variant="info">
                    <strong>Ready to split company:</strong>
                    <br />
                    Source: {getSelectedCompany()?.name}
                    <br />
                    Fiscal Year: {getSelectedFiscalYear()?.name || getSelectedFiscalYear()?.Name}
                    <br />
                    New Company: {formData.newCompanyName}
                    <br />
                    {formData.deleteAfterSplit && (
                        <>
                            <br />
                            <FaExclamationTriangle className="text-warning me-1" />
                            <strong>Warning:</strong> The selected fiscal year will be removed from the source company.
                        </>
                    )}
                    <br />
                    <br />
                    Click "Start Split" to begin the process.
                </Alert>
            )}

            {loading && (
                <div className="mb-4">
                    <div className="d-flex justify-content-between align-items-center mb-2">
                        <span>Progress: {progress}%</span>
                        <Badge bg="primary">
                            <span className="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
                            Processing...
                        </Badge>
                    </div>
                    <ProgressBar
                        now={progress}
                        label={`${progress}%`}
                        className="mb-3"
                        striped={progress < 100}
                        animated={progress < 100}
                    />
                </div>
            )}

            {splitComplete && splitResult && (
                <Alert variant="success">
                    <strong>✓ Split Completed Successfully!</strong>
                    <br />
                    {splitResult.message || 'Company split completed successfully'}
                    {splitResult.data && (
                        <>
                            <hr />
                            <small>
                                New Company: {splitResult.data.newCompany?.name}
                                <br />
                                New Fiscal Year: {splitResult.data.newFiscalYear?.name}
                                {splitResult.data.statistics && (
                                    <>
                                        <br />
                                        Items Copied: {splitResult.data.statistics.itemsCopied || splitResult.data.statistics.ItemsCopied || 0}
                                        <br />
                                        Accounts Copied: {splitResult.data.statistics.accountsCopied || splitResult.data.statistics.AccountsCopied || 0}
                                    </>
                                )}
                            </small>
                        </>
                    )}
                </Alert>
            )}

            {processLog.length > 0 && !splitComplete && (
                <Card className="mb-4">
                    <Card.Header>
                        <strong>Process Log</strong>
                    </Card.Header>
                    <Card.Body style={{ maxHeight: '200px', overflowY: 'auto', fontFamily: 'monospace', fontSize: '12px' }}>
                        {processLog.map((log, index) => (
                            <div key={index} className="border-bottom pb-1 mb-1">
                                <span className="text-muted">[{log.timestamp}]</span> {log.message}
                            </div>
                        ))}
                    </Card.Body>
                </Card>
            )}

            {error && !splitComplete && (
                <Alert variant="danger">
                    <strong>Error:</strong> {error}
                    <br />
                    <small>Please check your connection and try again.</small>
                </Alert>
            )}
        </div>
    );

    const renderStepContent = () => {
        switch (step) {
            case 1: return renderStep1();
            case 2: return renderStep2();
            case 3: return renderStep3();
            default: return null;
        }
    };

    const getStepTitle = () => {
        switch (step) {
            case 1: return 'Select Source';
            case 2: return 'New Company Details';
            case 3: return 'Split Company';
            default: return '';
        }
    };

    const handleClose = () => {
        if (!loading) {
            reset();
            onHide();
        }
    };

    return (
        <Modal show={show} onHide={handleClose} size="lg" centered backdrop={loading ? 'static' : true}>
            <Modal.Header closeButton={!loading}>
                <Modal.Title>
                    <div>
                        <div className="d-flex align-items-center">
                            <FaBuilding className="me-2 text-primary" />
                            Split Company by Fiscal Year
                        </div>
                        {!splitComplete && (
                            <small className="text-muted fs-6">{getStepTitle()}</small>
                        )}
                    </div>
                </Modal.Title>
            </Modal.Header>

            <Modal.Body>
                {!loading && !splitComplete && (
                    <div className="steps mb-4">
                        <Row className="text-center">
                            <Col>
                                <div className={`step ${step >= 1 ? 'active' : ''} d-flex flex-column align-items-center`}>
                                    <div className={`rounded-circle mb-2 d-flex align-items-center justify-content-center ${step >= 1 ? 'bg-primary' : 'bg-secondary'} text-white`}
                                        style={{ width: '30px', height: '30px' }}>
                                        1
                                    </div>
                                    <small>Select Source</small>
                                </div>
                            </Col>
                            <Col>
                                <div className={`step ${step >= 2 ? 'active' : ''} d-flex flex-column align-items-center`}>
                                    <div className={`rounded-circle mb-2 d-flex align-items-center justify-content-center ${step >= 2 ? 'bg-primary' : 'bg-secondary'} text-white`}
                                        style={{ width: '30px', height: '30px' }}>
                                        2
                                    </div>
                                    <small>New Company</small>
                                </div>
                            </Col>
                            <Col>
                                <div className={`step ${step >= 3 ? 'active' : ''} d-flex flex-column align-items-center`}>
                                    <div className={`rounded-circle mb-2 d-flex align-items-center justify-content-center ${step >= 3 ? 'bg-primary' : 'bg-secondary'} text-white`}
                                        style={{ width: '30px', height: '30px' }}>
                                        3
                                    </div>
                                    <small>Split</small>
                                </div>
                            </Col>
                        </Row>
                    </div>
                )}

                {renderStepContent()}
            </Modal.Body>

            <Modal.Footer>
                {!splitComplete && (
                    <>
                        {step > 1 && !loading && (
                            <Button variant="outline-secondary" onClick={handleBack}>
                                Back
                            </Button>
                        )}

                        {step < 3 && !loading && (
                            <Button variant="primary" onClick={handleNext}>
                                Next
                            </Button>
                        )}

                        {step === 3 && !loading && (
                            <Button variant="success" onClick={handleSubmit}>
                                Start Split
                            </Button>
                        )}

                        {loading && (
                            <Button variant="danger" onClick={cancelSplit}>
                                Cancel
                            </Button>
                        )}

                        <Button
                            variant="secondary"
                            onClick={handleCancel}
                            disabled={loading}
                        >
                            Cancel
                        </Button>
                    </>
                )}

                {splitComplete && (
                    <Button variant="primary" onClick={handleClose}>
                        Close
                    </Button>
                )}
            </Modal.Footer>
        </Modal>
    );
};

export default CompanySplitWizard;