// components/CompanySplitWizard.js
import React, { useState, useEffect } from 'react';
import {
    Modal,
    Button,
    Form,
    Card,
    Alert,
    ProgressBar,
    Row,
    Col,
    Badge,
    InputGroup,
    Spinner,
    ListGroup,
    Table
} from 'react-bootstrap';
import {
    FaBuilding,
    FaExclamationTriangle,
    FaInfoCircle,
    FaSync,
    FaCheckCircle,
    FaTimesCircle,
    FaArrowRight,
    FaCalendar,
    FaArrowLeft,
    FaDatabase,
    FaFileAlt,
    FaUsers,
    FaBoxes,
    FaMoneyBillWave,
    FaClipboardList,
    FaClock,
    FaCheck,
    FaSpinner,
    FaChevronRight,
    FaChevronLeft
} from 'react-icons/fa';
import useCompanySplit from '../hooks/useCompanySplit';


const CompanySplitWizard = ({ show, onHide, companies, fiscalYears, currentCompany, onSuccess }) => {
    const [step, setStep] = useState(1);
    const [formData, setFormData] = useState({
        sourceCompanyId: '',
        fiscalYearId: '',
        newCompanyName: '',
        deleteAfterSplit: false,
        includeTransactions: true,
        includeInventory: true,
        includeAccounts: true
    });
    const [validationErrors, setValidationErrors] = useState({});
    const [autoGeneratedName, setAutoGeneratedName] = useState('');
    const [splitComplete, setSplitComplete] = useState(false);
    const [splitResult, setSplitResult] = useState(null);
    const [estimatedTime, setEstimatedTime] = useState('2-5 minutes');

    const {
        loading,
        error,
        progress,
        processLog,
        splitCompanyWithSSE,
        cancelSplit,
        reset
    } = useCompanySplit();

    useEffect(() => {
        if (show) {
            if (currentCompany) {
                setFormData(prev => ({
                    ...prev,
                    sourceCompanyId: currentCompany.id || currentCompany._id
                }));
            }
            reset();
            setStep(1);
            setAutoGeneratedName('');
            setSplitComplete(false);
            setSplitResult(null);
            setEstimatedTime('2-5 minutes');
        }
    }, [show, currentCompany, reset]);

    useEffect(() => {
        if (formData.sourceCompanyId && formData.fiscalYearId) {
            generateCompanyName();
            estimateProcessingTime();
        }
    }, [formData.sourceCompanyId, formData.fiscalYearId]);

    const generateCompanyName = () => {
        const sourceCompany = companies.find(c => (c.id || c._id) === formData.sourceCompanyId);
        const fiscalYear = fiscalYears.find(fy => (fy.id || fy._id) === formData.fiscalYearId);

        if (sourceCompany && fiscalYear) {
            const newName = `${sourceCompany.name} (${fiscalYear.name || fiscalYear.Name})`;
            setAutoGeneratedName(newName);
            setFormData(prev => ({
                ...prev,
                newCompanyName: newName
            }));
        }
    };

    const estimateProcessingTime = () => {
        // Estimate based on data size (you can enhance this with actual data counts)
        const estimatedMinutes = Math.floor(Math.random() * 3) + 2;
        setEstimatedTime(`${estimatedMinutes}-${estimatedMinutes + 2} minutes`);
    };

    const handleInputChange = (field, value) => {
        setFormData(prev => ({
            ...prev,
            [field]: value
        }));

        if (validationErrors[field]) {
            setValidationErrors(prev => ({
                ...prev,
                [field]: ''
            }));
        }
    };

    const handleRegenerateName = () => {
        generateCompanyName();
    };

    const validateStep1 = () => {
        const errors = {};

        if (!formData.sourceCompanyId) {
            errors.sourceCompanyId = 'Please select a source company';
        }

        if (!formData.fiscalYearId) {
            errors.fiscalYearId = 'Please select a fiscal year';
        }

        setValidationErrors(errors);
        return Object.keys(errors).length === 0;
    };

    const validateStep2 = () => {
        const errors = {};

        if (!formData.newCompanyName?.trim()) {
            errors.newCompanyName = 'Please enter a name for the new company';
        } else if (formData.newCompanyName.length < 2) {
            errors.newCompanyName = 'Company name must be at least 2 characters long';
        }

        setValidationErrors(errors);
        return Object.keys(errors).length === 0;
    };

    const handleNext = () => {
        if (step === 1 && validateStep1()) {
            setStep(2);
        } else if (step === 2 && validateStep2()) {
            setStep(3);
        }
    };

    const handleBack = () => {
        setStep(step - 1);
    };

    const handleCancel = () => {
        if (loading) {
            cancelSplit();
        }
        reset();
        onHide();
    };

    const handleSubmit = async () => {
        try {
            const result = await splitCompanyWithSSE(formData);

            if (result && !result.cancelled) {
                if (result.data && result.data.newCompany) {
                    setSplitComplete(true);
                    setSplitResult(result);

                    setTimeout(() => {
                        if (onSuccess) {
                            onSuccess();
                        }
                        onHide();
                    }, 3000);
                } else if (result.success === false) {
                    setError(result.message || 'Split failed');
                } else if (result.success === true || result.message) {
                    setSplitComplete(true);
                    setSplitResult(result);

                    setTimeout(() => {
                        if (onSuccess) {
                            onSuccess();
                        }
                        onHide();
                    }, 3000);
                } else {
                    if (result.newCompany || result.data) {
                        setSplitComplete(true);
                        setSplitResult(result);

                        setTimeout(() => {
                            if (onSuccess) {
                                onSuccess();
                            }
                            onHide();
                        }, 3000);
                    } else {
                        setError('Split completed but no company data was returned');
                    }
                }
            }
        } catch (err) {
            console.error('Split failed:', err);
        }
    };

    const getSelectedCompany = () => {
        return companies.find(c => (c.id || c._id) === formData.sourceCompanyId);
    };

    const getSelectedFiscalYear = () => {
        return fiscalYears.find(fy => (fy.id || fy._id) === formData.fiscalYearId);
    };

    const getFilteredFiscalYears = () => {
        if (!formData.sourceCompanyId) return [];
        return fiscalYears.filter(fy => {
            const companyId = fy.companyId || fy.company || fy.company_id || fy.CompanyId;
            return companyId === formData.sourceCompanyId;
        });
    };

    const StepIndicator = ({ number, label, isActive, isCompleted }) => (
        <div className="d-flex align-items-center">
            <div className="position-relative">
                <div
                    className={`rounded-circle d-flex align-items-center justify-content-center ${isCompleted ? 'bg-success' : isActive ? 'bg-primary' : 'bg-secondary'} text-white`}
                    style={{ width: '40px', height: '40px', fontSize: '14px', fontWeight: 'bold' }}
                >
                    {isCompleted ? <FaCheck size={16} /> : number}
                </div>
                {isCompleted && (
                    <div className="position-absolute top-0 end-0 translate-middle">
                        <FaCheckCircle className="text-success" size={16} />
                    </div>
                )}
            </div>
            <div className="ms-2">
                <div className="fw-bold" style={{ fontSize: '13px' }}>{label}</div>
                <div style={{ fontSize: '11px', color: isActive ? '#0d6efd' : '#6c757d' }}>
                    {isActive ? 'Current step' : isCompleted ? 'Completed' : 'Pending'}
                </div>
            </div>
        </div>
    );

    const renderStep1 = () => (
        <div className="py-2">
            <h5 className="mb-4 d-flex align-items-center">
                <span className="bg-primary bg-opacity-10 rounded-3 p-2 me-3">
                    <FaBuilding className="text-primary" size={20} />
                </span>
                Select Source Company & Fiscal Year
            </h5>

            <Row>
                <Col lg={7}>
                    <Form.Group className="mb-4">
                        <Form.Label className="fw-semibold">
                            <FaBuilding className="me-2 text-primary" />
                            Source Company <span className="text-danger">*</span>
                        </Form.Label>
                        <Form.Select
                            value={formData.sourceCompanyId}
                            onChange={(e) => handleInputChange('sourceCompanyId', e.target.value)}
                            isInvalid={!!validationErrors.sourceCompanyId}
                            className="py-2"
                        >
                            <option value="">Select a company</option>
                            {companies.map(company => (
                                <option key={company.id || company._id} value={company.id || company._id}>
                                    {company.name}
                                    {(company.id === currentCompany?.id || company._id === currentCompany?._id) && ' (Current)'}
                                </option>
                            ))}
                        </Form.Select>
                        <Form.Control.Feedback type="invalid">
                            {validationErrors.sourceCompanyId}
                        </Form.Control.Feedback>
                    </Form.Group>

                    <Form.Group className="mb-4">
                        <Form.Label className="fw-semibold">
                            <FaCalendar className="me-2 text-primary" />
                            Fiscal Year to Split <span className="text-danger">*</span>
                        </Form.Label>
                        <Form.Select
                            value={formData.fiscalYearId}
                            onChange={(e) => handleInputChange('fiscalYearId', e.target.value)}
                            isInvalid={!!validationErrors.fiscalYearId}
                            disabled={!formData.sourceCompanyId}
                            className="py-2"
                        >
                            <option value="">Select fiscal year</option>
                            {getFilteredFiscalYears().map(fiscalYear => (
                                <option key={fiscalYear.id || fiscalYear._id} value={fiscalYear.id || fiscalYear._id}>
                                    {fiscalYear.name || fiscalYear.Name}
                                    ({fiscalYear.startDate
                                        ? new Date(fiscalYear.startDate).toLocaleDateString()
                                        : fiscalYear.startDateNepali || 'N/A'}
                                    - {fiscalYear.endDate
                                        ? new Date(fiscalYear.endDate).toLocaleDateString()
                                        : fiscalYear.endDateNepali || 'N/A'})
                                    {fiscalYear.isActive && ' ★'}
                                </option>
                            ))}
                        </Form.Select>
                        <Form.Control.Feedback type="invalid">
                            {validationErrors.fiscalYearId}
                        </Form.Control.Feedback>
                        <Form.Text className="text-muted">
                            <FaInfoCircle className="me-1" />
                            This fiscal year's data will be separated into a new company
                        </Form.Text>
                    </Form.Group>
                </Col>
                <Col lg={5}>
                    {formData.sourceCompanyId && formData.fiscalYearId && (
                        <Card className="bg-light border-0">
                            <Card.Body>
                                <div className="d-flex align-items-center text-success">
                                    <FaCheckCircle className="me-2" />
                                    <small>Ready to proceed to next step</small>
                                </div>
                            </Card.Body>
                        </Card>
                    )}
                </Col>
            </Row>
        </div>
    );

    const renderStep2 = () => (
        <div className="py-2">
            <h5 className="mb-4 d-flex align-items-center">
                <span className="bg-primary bg-opacity-10 rounded-3 p-2 me-3">
                    <FaBuilding className="text-primary" size={20} />
                </span>
                New Company Details
            </h5>

            <Row>
                <Col lg={7}>
                    <Form.Group className="mb-4">
                        <Form.Label className="fw-semibold">
                            New Company Name <span className="text-danger">*</span>
                        </Form.Label>
                        <InputGroup>
                            <Form.Control
                                type="text"
                                placeholder="Enter name for the new company"
                                value={formData.newCompanyName}
                                onChange={(e) => handleInputChange('newCompanyName', e.target.value)}
                                isInvalid={!!validationErrors.newCompanyName}
                                className="py-2"
                            />
                            {/* <Button
                                variant="outline-secondary"
                                onClick={handleRegenerateName}
                                title="Regenerate name from source company and fiscal year"
                                className="d-flex align-items-center"
                            >
                                <FaSync />
                            </Button> */}
                        </InputGroup>
                        <Form.Control.Feedback type="invalid">
                            {validationErrors.newCompanyName}
                        </Form.Control.Feedback>
                    </Form.Group>
                    <Form.Group>
                        <Form.Check
                            type="checkbox"
                            label={
                                <div>
                                    <strong className="text-danger">
                                        <FaExclamationTriangle className="me-2" />
                                        Remove splited fiscal year?
                                    </strong>
                                    <br />
                                    <small className="text-muted">
                                        This will remove the selected fiscal year from the source company.
                                    </small>
                                </div>
                            }
                            checked={formData.deleteAfterSplit}
                            onChange={(e) => handleInputChange('deleteAfterSplit', e.target.checked)}
                        />
                    </Form.Group>
                </Col>
                <Col lg={5}>
                    <Card className="border-warning bg-warning bg-opacity-10">
                        <Card.Body>
                            <h6 className="fw-bold mb-3 text-warning">
                                <FaExclamationTriangle className="me-2" />
                                Important Information
                            </h6>
                            <ul className="list-unstyled small">
                                <li className="mb-2 d-flex">
                                    <FaInfoCircle className="text-info me-2 mt-1" />
                                    <span>Do not close this window until the process is complete.</span>
                                </li>
                            </ul>
                        </Card.Body>
                    </Card>
                </Col>
            </Row>
        </div>
    );

    const renderStep3 = () => (
        <div className="py-2">
            <h5 className="mb-4 d-flex align-items-center">
                <span className={`rounded-3 p-2 me-3 ${splitComplete ? 'bg-success bg-opacity-10' : 'bg-primary bg-opacity-10'}`}>
                    {splitComplete ? (
                        <FaCheckCircle className="text-success" size={20} />
                    ) : loading ? (
                        <FaSpinner className="text-primary fa-spin" size={20} />
                    ) : (
                        <FaBuilding className="text-primary" size={20} />
                    )}
                </span>
                {splitComplete ? 'Split Completed Successfully!' : loading ? 'Processing Split...' : 'Ready to Split'}
            </h5>

            {!loading && !error && !splitComplete && (
                <Card className="border-info bg-info bg-opacity-10 mb-4">
                    <Card.Body>
                        <Row className="align-items-center">
                            <Col lg={8}>
                                <h6 className="fw-bold mb-2">Split Summary</h6>
                                <div className="row small">
                                    <div className="col-6">
                                        <span className="text-muted">Source Company:</span>
                                        <div className="fw-semibold">{getSelectedCompany()?.name}</div>
                                    </div>
                                    <div className="col-6">
                                        <span className="text-muted">Fiscal Year:</span>
                                        <div className="fw-semibold">{getSelectedFiscalYear()?.name || getSelectedFiscalYear()?.Name}</div>
                                    </div>
                                    <div className="col-6 mt-2">
                                        <span className="text-muted">New Company:</span>
                                        <div className="fw-semibold text-primary">{formData.newCompanyName}</div>
                                    </div>
                                    <div className="col-6 mt-2">
                                        <span className="text-muted">Action:</span>
                                        <div className="fw-semibold">
                                            {formData.deleteAfterSplit ? (
                                                <span className="text-danger">Remove from source</span>
                                            ) : (
                                                <span className="text-success">Keep in source</span>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            </Col>
                            <Col lg={4} className="text-lg-end mt-3 mt-lg-0">
                                <div className="d-flex flex-column align-items-lg-end">
                                    <Badge bg="info" className="mb-1">
                                        <FaClock className="me-1" />
                                        Est. Time: {estimatedTime}
                                    </Badge>
                                    <small className="text-muted">
                                        <FaInfoCircle className="me-1" />
                                        Ready to proceed
                                    </small>
                                </div>
                            </Col>
                        </Row>
                    </Card.Body>
                </Card>
            )}

            {loading && (
                <div className="mb-4">
                    <div className="d-flex justify-content-between align-items-center mb-2">
                        <div>
                            <Badge bg="primary" className="mb-1">
                                <FaSpinner className="me-1 fa-spin" />
                                Processing
                            </Badge>
                            <div className="small text-muted">Please wait, this may take a few minutes...</div>
                        </div>
                        <div className="text-end">
                            <div className="fw-bold fs-4">{progress}%</div>
                            <small className="text-muted">Complete</small>
                        </div>
                    </div>
                    <ProgressBar
                        now={progress}
                        className="mb-3"
                        style={{ height: '12px' }}
                        variant={progress < 100 ? 'primary' : 'success'}
                        striped={progress < 100}
                        animated={progress < 100}
                    />
                    <div className="d-flex justify-content-between small text-muted">
                        <span>Starting</span>
                        <span>Processing data</span>
                        <span>Finalizing</span>
                    </div>
                </div>
            )}

            {processLog.length > 0 && !splitComplete && (
                <Card className="mb-4">
                    <Card.Header className="d-flex align-items-center bg-light">
                        <FaClipboardList className="me-2 text-primary" />
                        <strong>Process Log</strong>
                        <Badge bg="secondary" className="ms-2">{processLog.length}</Badge>
                    </Card.Header>
                    <Card.Body style={{ maxHeight: '200px', overflowY: 'auto', fontFamily: 'monospace', fontSize: '12px', padding: '8px' }}>
                        {processLog.map((log, index) => (
                            <div key={index} className="border-bottom pb-1 mb-1 d-flex align-items-start">
                                <span className="text-muted me-2" style={{ whiteSpace: 'nowrap' }}>
                                    [{log.timestamp}]
                                </span>
                                <span>{log.message}</span>
                            </div>
                        ))}
                    </Card.Body>
                </Card>
            )}

            {splitComplete && splitResult && (
                <Alert variant="success" className="mb-4">
                    <div className="d-flex align-items-start">
                        <FaCheckCircle className="me-3 mt-1" size={24} />
                        <div>
                            <strong className="d-block mb-2">Split Completed Successfully!</strong>
                            <p className="mb-2">{splitResult.message || 'Company split completed successfully'}</p>
                            {splitResult.data && (
                                <div className="small">
                                    <hr />
                                    <Row>
                                        <Col md={6}>
                                            <span className="text-muted">New Company:</span>
                                            <div className="fw-semibold">{splitResult.data.newCompany?.name}</div>
                                        </Col>
                                        <Col md={6}>
                                            <span className="text-muted">New Fiscal Year:</span>
                                            <div className="fw-semibold">{splitResult.data.newFiscalYear?.name}</div>
                                        </Col>
                                    </Row>
                                    {splitResult.data.statistics && (
                                        <Row className="mt-2">
                                            <Col md={4}>
                                                <Badge bg="info" className="d-flex align-items-center justify-content-center p-2">
                                                    <FaFileAlt className="me-1" />
                                                    Items: {splitResult.data.statistics.itemsCopied || splitResult.data.statistics.ItemsCopied || 0}
                                                </Badge>
                                            </Col>
                                            <Col md={4}>
                                                <Badge bg="success" className="d-flex align-items-center justify-content-center p-2">
                                                    <FaUsers className="me-1" />
                                                    Accounts: {splitResult.data.statistics.accountsCopied || splitResult.data.statistics.AccountsCopied || 0}
                                                </Badge>
                                            </Col>
                                            <Col md={4}>
                                                <Badge bg="warning" className="d-flex align-items-center justify-content-center p-2">
                                                    <FaMoneyBillWave className="me-1" />
                                                    Transactions: {splitResult.data.statistics.transactionsCopied || splitResult.data.statistics.TransactionsCopied || 0}
                                                </Badge>
                                            </Col>
                                        </Row>
                                    )}
                                </div>
                            )}
                        </div>
                    </div>
                </Alert>
            )}

            {error && !splitComplete && (
                <Alert variant="danger">
                    <strong>Error:</strong> {error}
                    <br />
                    <small>Please check your connection and try again.</small>
                </Alert>
            )}
        </div>
    );

    const renderStepContent = () => {
        switch (step) {
            case 1: return renderStep1();
            case 2: return renderStep2();
            case 3: return renderStep3();
            default: return null;
        }
    };

    const getStepTitle = () => {
        switch (step) {
            case 1: return 'Select Source';
            case 2: return 'New Company';
            case 3: return 'Split';
            default: return '';
        }
    };

    const handleClose = () => {
        if (!loading) {
            reset();
            onHide();
        }
    };

    return (
        <Modal show={show} onHide={handleClose} size="lg" centered backdrop={loading ? 'static' : true}>
            <Modal.Header closeButton={!loading} className="border-0 pb-0">
                <Modal.Title>
                    <div className="d-flex align-items-center">
                        <div>
                            <div className="fw-bold" style={{ fontSize: '1.1rem' }}>
                                Split Company by Fiscal Year
                            </div>
                        </div>
                    </div>
                </Modal.Title>
            </Modal.Header>

            <Modal.Body className="pt-3">
                {!loading && !splitComplete && (
                    <div className="mb-4 px-3">
                        <div className="d-flex justify-content-between align-items-center position-relative">
                            <div className="position-absolute top-50 start-0 end-0" style={{ height: '2px', backgroundColor: '#dee2e6', zIndex: 0, transform: 'translateY(-50%)' }}>
                                <div className="h-100" style={{
                                    width: `${((step - 1) / 2) * 100}%`,
                                    backgroundColor: '#0d6efd',
                                    transition: 'width 0.3s ease'
                                }} />
                            </div>
                            {[1, 2, 3].map((num) => {
                                const isActive = step === num;
                                const isCompleted = step > num;
                                return (
                                    <div key={num} className="d-flex flex-column align-items-center" style={{ zIndex: 1 }}>
                                        <div
                                            className={`rounded-circle d-flex align-items-center justify-content-center ${isCompleted ? 'bg-success' : isActive ? 'bg-primary' : 'bg-secondary'} text-white`}
                                            style={{ width: '36px', height: '36px', fontSize: '14px', fontWeight: 'bold' }}
                                        >
                                            {isCompleted ? <FaCheck size={14} /> : num}
                                        </div>
                                        <div className="mt-1" style={{ fontSize: '11px', fontWeight: isActive ? 'bold' : 'normal', color: isActive ? '#0d6efd' : '#6c757d' }}>
                                            {num === 1 ? 'Select' : num === 2 ? 'Details' : 'Split'}
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                )}

                {renderStepContent()}
            </Modal.Body>

            <Modal.Footer className="border-0 pt-0">
                {!splitComplete && (
                    <>
                        {step > 1 && !loading && (
                            <Button
                                variant="outline-secondary"
                                onClick={handleBack}
                                className="d-flex align-items-center"
                            >
                                <FaArrowLeft className="me-2" />
                                Back
                            </Button>
                        )}

                        {step < 3 && !loading && (
                            <Button
                                variant="primary"
                                onClick={handleNext}
                                className="d-flex align-items-center px-4"
                            >
                                Next
                                <FaArrowRight className="ms-2" />
                            </Button>
                        )}

                        {step === 3 && !loading && (
                            <Button
                                variant="success"
                                onClick={handleSubmit}
                                className="d-flex align-items-center px-4"
                            >
                                <FaCheck className="me-2" />
                                Start Split
                            </Button>
                        )}

                        {loading && (
                            <Button variant="danger" onClick={cancelSplit} className="d-flex align-items-center">
                                <FaTimesCircle className="me-2" />
                                Cancel
                            </Button>
                        )}

                        <Button
                            variant="secondary"
                            onClick={handleCancel}
                            disabled={loading}
                        >
                            Cancel
                        </Button>
                    </>
                )}

                {splitComplete && (
                    <Button variant="primary" onClick={handleClose} className="d-flex align-items-center px-4">
                        <FaCheck className="me-2" />
                        Close
                    </Button>
                )}
            </Modal.Footer>
        </Modal>
    );
};

export default CompanySplitWizard;